"""Add flow system models - Flow, FlowState, FlowTransition, FlowAction

Revision ID: 12885d274764
Revises: 
Create Date: 2025-08-09 10:42:09.192065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import JsonGettable


# revision identifiers, used by Alembic.
revision: str = '12885d274764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.Enum('CREATE_ORDER', 'TRACK_ORDER', 'CANCEL_ORDER', 'HANDLE_MPESA_PAYMENT', 'HANDLE_CASH_PAYMENT', 'HANDLE_PAYMENT_CONFIRMATION', 'SEND_WELCOME_MESSAGE', 'SEND_HELP_MESSAGE', 'SEND_PAYMENT_OPTIONS', 'CONTACT_SUPPORT', 'NO_ACTION', 'RESET_SESSION', name='actionname'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_name')
    )
    op.create_index(op.f('ix_flow_actions_id'), 'flow_actions', ['id'], unique=False)
    op.create_table('flow_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('state_type', sa.Enum('SEND_MESSAGE', 'AWAIT_RESPONSE', 'END_SESSION', name='statetype'), nullable=False),
    sa.Column('is_start_state', sa.Boolean(), nullable=False),
    sa.Column('state_config', JsonGettable(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_states_flow_id'), 'flow_states', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_states_id'), 'flow_states', ['id'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_state_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['start_state_id'], ['flow_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'is_active', name='uix_group_active_flow')
    )
    op.create_index(op.f('ix_flows_group_id'), 'flows', ['group_id'], unique=False)
    op.create_index(op.f('ix_flows_id'), 'flows', ['id'], unique=False)
    op.create_table('flow_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_state_id', sa.Integer(), nullable=False),
    sa.Column('target_state_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('KEYWORD', 'BUTTON_ID', 'ANY_TEXT', 'SYSTEM', name='triggertype'), nullable=False),
    sa.Column('trigger_value', sa.String(length=255), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['flow_actions.id'], ),
    sa.ForeignKeyConstraint(['source_state_id'], ['flow_states.id'], ),
    sa.ForeignKeyConstraint(['target_state_id'], ['flow_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_transitions_id'), 'flow_transitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_transitions_id'), table_name='flow_transitions')
    op.drop_table('flow_transitions')
    op.drop_index(op.f('ix_flows_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_group_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_flow_states_id'), table_name='flow_states')
    op.drop_index(op.f('ix_flow_states_flow_id'), table_name='flow_states')
    op.drop_table('flow_states')
    op.drop_index(op.f('ix_flow_actions_id'), table_name='flow_actions')
    op.drop_table('flow_actions')
    # ### end Alembic commands ###
