"""Update phone number validation and conversation state type

Revision ID: 2b024d67e07e
Revises: c975018df037
Create Date: 2025-08-14 08:19:04.229441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b024d67e07e'
down_revision: Union[str, None] = 'c975018df037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.alter_column('current_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('INITIAL', 'WELCOME', 'AWAITING_ORDER_DETAILS', 'AWAITING_PAYMENT', 'AWAITING_PAYMENT_CONFIRMATION', 'TRACKING_ORDER', 'WAITING_FOR_SUPPORT', 'IDLE', name='conversationstate'),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_active_group_id')
        batch_op.create_index(batch_op.f('ix_customers_active_group_id'), ['active_group_id'], unique=False)

    with op.batch_alter_table('flow_states', schema=None) as batch_op:
        batch_op.drop_index('ix_flow_state_is_start_state')
        batch_op.create_index(batch_op.f('ix_flow_states_is_start_state'), ['is_start_state'], unique=False)

    with op.batch_alter_table('flow_transitions', schema=None) as batch_op:
        batch_op.drop_index('ix_flow_transition_priority')
        batch_op.create_index(batch_op.f('ix_flow_transitions_priority'), ['priority'], unique=False)

    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_index('ix_flow_is_active')
        batch_op.create_index(batch_op.f('ix_flows_is_active'), ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_flows_is_active'))
        batch_op.create_index('ix_flow_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('flow_transitions', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_flow_transitions_priority'))
        batch_op.create_index('ix_flow_transition_priority', ['priority'], unique=False)

    with op.batch_alter_table('flow_states', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_flow_states_is_start_state'))
        batch_op.create_index('ix_flow_state_is_start_state', ['is_start_state'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_customers_active_group_id'))
        batch_op.create_index('ix_customer_active_group_id', ['active_group_id'], unique=False)

    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.alter_column('current_state',
               existing_type=sa.Enum('INITIAL', 'WELCOME', 'AWAITING_ORDER_DETAILS', 'AWAITING_PAYMENT', 'AWAITING_PAYMENT_CONFIRMATION', 'TRACKING_ORDER', 'WAITING_FOR_SUPPORT', 'IDLE', name='conversationstate'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###