"""add session_metadata field to conversation_sessions

Revision ID: 6593a5bd9ced
Revises: eff12dfd5134
Create Date: 2025-09-29 20:37:26.451030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6593a5bd9ced'
down_revision: Union[str, None] = 'eff12dfd5134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_sessions', sa.Column('session_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_sessions', 'session_metadata')
    # ### end Alembic commands ###
