"""Add cart recovery system

Revision ID: 8fde940613cc
Revises: phone_field_size_increase
Create Date: 2025-09-26 19:43:45.268654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
import os

# Add the project root to Python path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
import app.models

# revision identifiers, used by Alembic.
revision: str = '8fde940613cc'
down_revision: Union[str, None] = 'phone_field_size_increase'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('conversation_session_id', sa.Integer(), nullable=True),
    sa.Column('cart_data', app.models.JsonGettable(), nullable=True),
    sa.Column('estimated_total', sa.Float(), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ABANDONED', 'RECOVERED', 'EXPIRED', 'COMPLETED', name='cartstatus'), nullable=False),
    sa.Column('abandoned_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=False),
    sa.Column('recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_recovery_message_at', sa.DateTime(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_order_id', sa.Integer(), nullable=True),
    sa.Column('abandonment_reason', sa.Enum('PAYMENT_HESITATION', 'PRICING_CONCERN', 'DELIVERY_ISSUE', 'PRODUCT_UNAVAILABLE', 'CUSTOMER_DISTRACTION', 'TECHNICAL_ISSUE', 'UNKNOWN', name='abandonmentreason'), nullable=True),
    sa.Column('customer_sentiment', sa.String(length=50), nullable=True),
    sa.Column('ai_predicted_recovery_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['conversation_session_id'], ['conversation_sessions.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_sessions_customer_id'), 'cart_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cart_sessions_group_id'), 'cart_sessions', ['group_id'], unique=False)
    op.create_index(op.f('ix_cart_sessions_id'), 'cart_sessions', ['id'], unique=False)
    op.create_table('abandonment_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('analysis_period_start', sa.DateTime(), nullable=False),
    sa.Column('analysis_period_end', sa.DateTime(), nullable=False),
    sa.Column('total_cart_sessions', sa.Integer(), nullable=True),
    sa.Column('abandoned_sessions', sa.Integer(), nullable=True),
    sa.Column('abandonment_rate', sa.Float(), nullable=True),
    sa.Column('recovery_attempts', sa.Integer(), nullable=True),
    sa.Column('successful_recoveries', sa.Integer(), nullable=True),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.Column('revenue_recovered', sa.Float(), nullable=True),
    sa.Column('top_abandonment_reasons', app.models.JsonGettable(), nullable=True),
    sa.Column('abandonment_by_time_of_day', app.models.JsonGettable(), nullable=True),
    sa.Column('most_effective_recovery_messages', app.models.JsonGettable(), nullable=True),
    sa.Column('customer_segment_performance', app.models.JsonGettable(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandonment_analytics_group_id'), 'abandonment_analytics', ['group_id'], unique=False)
    op.create_index(op.f('ix_abandonment_analytics_id'), 'abandonment_analytics', ['id'], unique=False)
    op.create_table('cart_recovery_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_session_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('message_sent_at', sa.DateTime(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('ai_personalization_data', app.models.JsonGettable(), nullable=True),
    sa.Column('incentive_offered', app.models.JsonGettable(), nullable=True),
    sa.Column('customer_responded_at', sa.DateTime(), nullable=True),
    sa.Column('customer_response', sa.Text(), nullable=True),
    sa.Column('resulted_in_recovery', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESSFUL', 'FAILED', 'EXHAUSTED', name='recoverystatus'), nullable=False),
    sa.Column('message_delivered', sa.Boolean(), nullable=True),
    sa.Column('message_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_session_id'], ['cart_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_recovery_campaigns_cart_session_id'), 'cart_recovery_campaigns', ['cart_session_id'], unique=False)
    op.create_index(op.f('ix_cart_recovery_campaigns_id'), 'cart_recovery_campaigns', ['id'], unique=False)
    op.drop_index(op.f('ix_api_usage_logs_id'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.add_column('conversation_sessions', sa.Column('cart_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation_sessions', 'cart_sessions', ['cart_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_sessions', type_='foreignkey')
    op.drop_column('conversation_sessions', 'cart_session_id')
    op.create_table('api_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('api_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('api_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_usage_logs_pkey'))
    )
    op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_cart_recovery_campaigns_id'), table_name='cart_recovery_campaigns')
    op.drop_index(op.f('ix_cart_recovery_campaigns_cart_session_id'), table_name='cart_recovery_campaigns')
    op.drop_table('cart_recovery_campaigns')
    op.drop_index(op.f('ix_abandonment_analytics_id'), table_name='abandonment_analytics')
    op.drop_index(op.f('ix_abandonment_analytics_group_id'), table_name='abandonment_analytics')
    op.drop_table('abandonment_analytics')
    op.drop_index(op.f('ix_cart_sessions_id'), table_name='cart_sessions')
    op.drop_index(op.f('ix_cart_sessions_group_id'), table_name='cart_sessions')
    op.drop_index(op.f('ix_cart_sessions_customer_id'), table_name='cart_sessions')
    op.drop_table('cart_sessions')
    # ### end Alembic commands ###
