"""Add indexes and improve schema

Revision ID: c975018df037
Revises: 12885d274764
Create Date: 2025-08-14 08:11:09.411950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import ConversationState


# revision identifiers, used by Alembic.
revision: str = 'c975018df037'
down_revision: Union[str, None] = '12885d274764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_active_group_id'), 'customers', ['active_group_id'], unique=False)
    op.create_index(op.f('ix_flow_is_active'), 'flows', ['is_active'], unique=False)
    op.create_index(op.f('ix_flow_state_is_start_state'), 'flow_states', ['is_start_state'], unique=False)
    op.create_index(op.f('ix_flow_transition_priority'), 'flow_transitions', ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_transition_priority'), table_name='flow_transitions')
    op.drop_index(op.f('ix_flow_state_is_start_state'), table_name='flow_states')
    op.drop_index(op.f('ix_flow_is_active'), table_name='flows')
    op.drop_index(op.f('ix_customer_active_group_id'), table_name='customers')
    # ### end Alembic commands ###