"""Add enhanced inventory models

Revision ID: f4e015994771
Revises: 8fde940613cc
Create Date: 2025-09-29 06:34:32.788863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4e015994771'
down_revision: Union[str, None] = '8fde940613cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_logs_id'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.create_index(op.f('ix_cart_sessions_completed_order_id'), 'cart_sessions', ['completed_order_id'], unique=False)
    op.create_index(op.f('ix_cart_sessions_conversation_session_id'), 'cart_sessions', ['conversation_session_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_cart_session_id'), 'conversation_sessions', ['cart_session_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_customer_id'), 'conversation_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_inventory_logs_user_id'), 'inventory_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_delivery_status_customer_id'), 'message_delivery_status', ['customer_id'], unique=False)
    op.create_index(op.f('ix_message_delivery_status_order_id'), 'message_delivery_status', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_delivery_status_order_id'), table_name='message_delivery_status')
    op.drop_index(op.f('ix_message_delivery_status_customer_id'), table_name='message_delivery_status')
    op.drop_index(op.f('ix_inventory_logs_user_id'), table_name='inventory_logs')
    op.drop_index(op.f('ix_conversation_sessions_customer_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_cart_session_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_cart_sessions_conversation_session_id'), table_name='cart_sessions')
    op.drop_index(op.f('ix_cart_sessions_completed_order_id'), table_name='cart_sessions')
    op.create_table('api_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('api_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_method', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('api_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_usage_logs_pkey'))
    )
    op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    # ### end Alembic commands ###
